services: 
  backend: # first service 
    image: parag2608/flaskapp:latest  # fetches image from public repo in dockerhub
    ports:
      - "5000:5000"
    environment: # setting environment variables 
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
    depends_on:  # this service/container will start after mysql container only, this is done to avoid errors
      - mysql

  mysql: # second service
    image: mysql:5.7 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql # Mount sql script into container's /docker-entrypoint-initdb.d directory to get table automatically created
      - mysql-data:/var/lib/mysql # Mount the volume for MySQL data storage

volumes:      # creation of volume which is binded to your system/server/machine . even when the container goes down your data will persist. 
  mysql-data:     # on docker container its stored in /var/lib/mysql, on your machine its stored in /var/lib/docker/volumes


