apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service

spec: 
  selector: 
    app: two-tier-app

  ports:
    - protocol: TCP
      port: 80                  # we are mapping internal port of deployment to container port 50000, and two-tier-app-service port 30007 is mapped to 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort
